### ISSUE TITLE
Struktura ticketů

### ISSUE THREAD

**Issue by LordShedy** [LordShedy/unidens.com#2]
Pro zachování přehlednosti navrhuji používat následující strukturu ticketů:

 ### Popis
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi quis orci odio. Suspendisse vel lorem quis ex ornare commodo et a urna. Quisque vitae mollis lorem, vel bibendum libero. Integer hendrerit, arcu sed rhoncus fermentum, massa ex ornare urna, nec imperdiet ligula arcu quis sem.

### Postup reprodukce
1. nullam a mi justo augue sed,
2. duis viverra odio ut magna facilisis varius,
3. eros quam rhoncus turpis.

### Obrázek
![image](https://user-images.githubusercontent.com/1622827/52368914-d53f7700-2a4f-11e9-8f30-0670064767ca.png)

**Comment by biel00** [comment]
### Súhlasím, a týmto uzatváram Issue - štruktúra ticketov je štandardizovaná do vyššie spomínanej formy.
