### ISSUE TITLE
Rozjet dokumentaci na GitHubu

### ISSUE THREAD

**Issue by LordShedy** [LordShedy/unidens.com#20]
### Cíl
Je jasné, kde a jakým způsobem je vedená dokumentace tohoto projektu.

**Comment by biel00** [comment]
### Dočka
Dokumentácia bude písaná vo Wiki, alebo nejakým iným spôsobom? (zložka s dokumentami priamo v projekte, Issues, atď...)

**Comment by LordShedy** [comment]
Jsem pro minimální (vzhledem k malé škále projektu), která by byla zde na GitHubu, pouze v podobě jednotlivých stránek definující různé aspekty projektu.

**Comment by biel00** [comment]
Jednotlivé stránky teda chápem ako nejaké textové súbory priamo v projekte, správne?

**Comment by LordShedy** [comment]
Ne, jednotlivé stránky jsou uložené někde na GitHubových serverech, odděleny od projektového repozitáře.

**Comment by biel00** [comment]
Absolútne som stratený kamo 😅

**Comment by LordShedy** [comment]
Naše dokumentace bude na GitHubu (tenhle repozitář, záložka Wiki), to je vše, co je třeba o ní vědět.

**Comment by biel00** [comment]
Jop, mal si hneď povedať.
