### ISSUE TITLE
CSS technologie

### ISSUE THREAD

**Issue by LordShedy** [LordShedy/unidens.com#22]
### Popis
Pracovat ve vanilla CSS není úplně přehledné a pohodlné, navrhuji proto vybrat jeden z CSS preprocesorů a používat je. Na výběr máme:
-  LESS,
- SASS,
- Stylus.

Já mám zkušenost se SASSem, tedy bych volil jej, není vyloženě velký rozdíl, jaký použijeme, ale měli bychom nějaký, protože to umožňuje věci, které čistému CSS chybí (vytvářet pseudotřídy, cykly, ifky, strukturování a větvení a pod.). Není težké se jakýkoliv naučit, nejjednodušší je prej LESS, ale já jsem se během chvíle naučil i ten SASS a tedy bych i v tom rád pokračoval.

### Cíl
Technologie na CSS je vybrána.

**Comment by biel00** [comment]
Pozeral som sa na SASS, a myslím že môže byť. Je to príjemné vylepšenie CSSka, u ktorého sa mi páčia tie featury, išiel by som s tým.

**Comment by LordShedy** [comment]
Super, výborně. Tedy na CSS budeme používat preprocesor SASS.
