### ISSUE TITLE
Jazykové řešení

### ISSUE THREAD

**Issue by LordShedy** [LordShedy/unidens.com#26]
### Popis

Web bude ve 4 jazykových variantách. Je třeba se rozhodnout, jakým způsobem to bude řešeno. Možnosti jsou následující:

- 4 weby na subdoméně (cz.unidens.com, en.unidens.com, de.unidens.com…),
- 1 web a 4 cizojazyčné databáze (přepínání pomocí nějakého flagu na webu, tedy PHP verze),

Chceme, abychom mohli mít 1 vývoj, ideálně neduplikovat weby, ale jen měnit na nich jejich data. Nejjednodušší řešení preferováno.

### Cíl
Vybrali jsme způsob, jakým budeme řešit cizojazyčnost webu.

**Comment by LordShedy** [comment]
Další možností je to udělat přes Javascript:

https://youtu.be/PaJrDAmrOB4

**Comment by biel00** [comment]
Hotovo, dohodli sme sa na PHP backende, ktorý bude generovať HTML a načítavať text z databáze.
