### ISSUE TITLE
Barevné schéma

### ISSUE THREAD

**Issue by LordShedy** [LordShedy/unidens.com#3]
### Popis
Je třeba navrhnout 2 barevné schéma, měly by existovat barvy pro:
- pozadí (_background color_),
- primární prvky (_primary color_),
- neutrální prvky (_secondary color_),
- doplňková barva (_highlight color_).

Barvy by měly být kontrastní, ale ne do očí bijící (žádná čistě bílá, čistě černá).

### Cíl
Existuje schválené barevné schéma pro web (v jeho hexadecimální podobě).

**Comment by biel00** [comment]
### Zachovanie business tváre

Generoval som si nové farebné palety, keď mi napadlo že zmena stránky a zároveň zmena farby by mohla docela uškodiť businessu čo sa týka stálych zákazníkov (určite sú aj takí). Zmena designu je docela veľká vec, preto by som farby ponechal.

**Comment by LordShedy** [comment]
Souhlasím, do příštího milníku vytvořím paletu dle původních barev.

**Comment by LordShedy** [comment]
### Popisek
Tohle je paleta picklá dle barev aktuálně se nacházející na webu.

### Paleta
![vysledna_paleta](https://coolors.co/export/png/141414-ced1d5-f569ad-ffffff-000000)

**Comment by LordShedy** [comment]
### Popise
Na origo paletě se mi nelíbí ty **vyloženě** čiré barvy (čistě bílá a čistě černá). Mám za to, že v takové podobě by na webu bejt neměly, ale nedokáži uvést argument proč, každopádně na finální paletu navrhuji tuto, lehce upravaenou z té aktuální.

### Paleta
![upravena_paleta](https://coolors.co/export/png/141414-ced1d5-f569ad-f2f4f3-0d0f05)

 ### Odkaz
[https://coolors.co/export/png/141414-ced1d5-f569ad-f2f4f3-0d0f05](https://coolors.co/export/png/141414-ced1d5-f569ad-f2f4f3-0d0f05)

**Comment by biel00** [comment]
Ani mne sa to nepáči v tých farbách v akých je to teraz, ten kontrast je proste príliš ostrý.. NO tvoj nový návrh mi príde ako úprava tej prvej palety, ktorú sme sem už raz pridávali. Nemám s tým problém, no tie dve čierne mi prídu ako trošku overkill, tam by stačil aj jeden odtieň.

**Comment by LordShedy** [comment]
### Popis
Naše finální paleta se bude skládat z následující 4 barev:

| barva  | název barvy | kód barvy |
|--------|-------------|-----------|
| černá  | licorice    | #141414   |
| šedá   | light gray  | #ced1d5   |
| růžová | hot pink    | #f569ad   |
| bílá   | baby powder | #fbfcfb   |

### Paleta
![image](https://user-images.githubusercontent.com/1622827/60245578-2ea02980-98bd-11e9-9f11-7b7e22d139b3.png)

**Comment by LordShedy** [comment]
@biel00 souhlasíš s touhle paletou či se ti ta bílá ještě nezdá?

**Comment by biel00** [comment]
Absolútne.
