### ISSUE TITLE
Free hosting

### ISSUE THREAD

**Issue by LordShedy** [LordShedy/unidens.com#7]
### Popis
Zjistit, zda a jak by šel zaimplementovat free hosting ve stylu Amazon AWS (zjistit i jak by to šlo s hostingem na AWS).

### Cíl
Mít vybraný nějaký hosting, issue lze uzavřít ve chvíli, kdy už máme nějaký hosting zvolen, a tedy je diskuze na téma jaký zvolit zbytečná.

**Comment by biel00** [comment]
### AWS má Free Tier
Free tier Amazonu dovoľuje prevádzkovať VMky 750 hodín mesačne (30*24=720) po dobu jedného roku zadarmo, čo je velice fajn, minimálne pre nás na dev.
Bližšie info [na tomto linku](https://aws.amazon.com/ec2/pricing/)

Je tu však obmedzenie na VM, ktoré môžeme prevádzkovať. Môžeme mať len T2.micro instancie.
Bližšie info [na tomto odkaze](https://aws.amazon.com/ec2/instance-types/)

Na ostré produkčné nasadenie by som v tom prípade asi odporúčal platený hosting.

**Comment by biel00** [comment]
### GCP má Free Tier
Free tier od Googlu zahŕňa kredit 300$ na 12 mesiacov, a môžnosť využitia jednej f1-micro VM z regiónu North America (pravdepodobne je príliš ďaleko, lepšie by boli EU regióny). F1-micro VM od Googlu má zároveň o 400MB RAM menej ako T2.micro od Amazonu, preto by som ju pravdepodobne išiel radšej k Amazonu na free hosting. 

Na záver by som dodal že o Azure sa nemá zmysel baviť, do Microsoftu proste nejdem... :X

**Comment by LordShedy** [comment]
Mohl bych poprosit o objasnění, co to jsou T2.micro a F1-micro VM?

**Comment by biel00** [comment]
Malé VM, každá s jedným CPU, s tým že T.2-micro od Amazonu má 1GB RAM a F1-micro od Googlu má 600 MB  RAM. Ukladací priestor na oboch je niekoľko GB, s tým že bude úplne stačiť na minimálny CentOS (ak sa na ňom zhodneme) a webový server so stránkou, prípadne niekoľkými verziami stránky

**Comment by LordShedy** [comment]
### Shrnutí
Shodli jsme se na tom, že tohle by nás stálo mnohé zbytečné práce navíc, tedy půjdeme pro standardní placený hosting (#11).
